version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pastelaria-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./vendor:/var/www/html/vendor
    networks:
      - pastelaria-network

  webserver:
    image: nginx:alpine
    container_name: pastelaria-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - pastelaria-network
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: pastelaria-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: pastelaria
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - pastelaria-network

networks:
  pastelaria-network:
    driver: bridge

volumes:
  dbdata:
